In [1]:
import tensorflow as tf
import numpy as np

In [25]:
x_data = [[1,2,1,1],
          [2,1,3,2],
          [3,1,3,4],
          [4,1,5,5],
          [1,7,5,5],
          [1,2,5,6],
          [1,6,6,6],
          [1,7,7,7]]

#one hot encoding
y_data = [[0,0,1],
          [0,0,1],
          [0,0,1],
          [0,1,0],
          [0,1,0],
          [0,1,0],
          [1,0,0],
          [1,0,0]]

In [26]:
#convert into numpy and float format 

x_data = np.asarray(x_data,dtype=np.float32)
y_data = np.asarray(y_data,dtype=np.float32)

nb_classes = 3 #num classes

dataset = tf.data.Dataset.from_tensor_slices((x_data,y_data)).batch(len(x_data))

In [27]:
# Weights and bias setting
W = tf.Variable(tf.random.normal([4,nb_classes]), name = 'weight')
b = tf.Variable(tf.random.normal([nb_classes]), name = 'bias')

In [28]:
print(W,b)

<tf.Variable 'weight:0' shape=(4, 3) dtype=float32, numpy=
array([[-2.299928  ,  0.23382339,  0.6433769 ],
       [ 0.837943  , -0.21832135,  1.4886992 ],
       [-1.7832663 ,  0.6388995 ,  0.14891686],
       [-2.2672026 ,  0.42680073,  0.18071367]], dtype=float32)> <tf.Variable 'bias:0' shape=(3,) dtype=float32, numpy=array([ 0.26339096, -0.05497049,  0.18925448], dtype=float32)>


In [33]:
def softmax_fn(features) :
  hypothesis = tf.nn.softmax(tf.matmul(features, W) + b)
  return hypothesis

# cost function : cross-entropy

def cost_fn(features,labels) :
  hypothesis = softmax_fn(features)
  cost = tf.reduce_mean(-tf.reduce_sum(labels * tf.math.log(hypothesis), axis = 1))
  return cost

def grad(hypothesis, features, labels) :
  with tf.GradientTape() as tape :
    loss_value = cost_fn(features, labels)
  return tape.gradient(loss_value, [W,b])

optimizer = tf.keras.optimizers.SGD(learning_rate = 0.01)

epochs = 3000

for step in range(epochs + 1) :
  for features, labels in iter(dataset) :
    hypothesis = softmax_fn(features)
    grads = grad(hypothesis, features, labels)
    optimizer.apply_gradients(grads_and_vars = zip(grads,[W,b]))

    if step % 300 == 0 :
      print("iter: {}, Loss: {:.4f}".format(step, cost_fn(features, labels)))


iter: 0, Loss: 9.6814
iter: 300, Loss: 0.7818
iter: 600, Loss: 0.6005
iter: 900, Loss: 0.5205
iter: 1200, Loss: 0.4888
iter: 1500, Loss: 0.4674
iter: 1800, Loss: 0.4498
iter: 2100, Loss: 0.4346
iter: 2400, Loss: 0.4212
iter: 2700, Loss: 0.4090
iter: 3000, Loss: 0.3978


In [35]:
a = softmax_fn(x_data)

print(a)
print(tf.argmax(a,1))  # 가설을 통해 예측값
print(tf.argmax(y_data, 1))  # 실제 값

tf.Tensor(
[[8.4266253e-03 4.5521971e-02 9.4605136e-01]
 [8.4934365e-03 2.2409101e-01 7.6741546e-01]
 [2.2550140e-04 3.5035801e-01 6.4941651e-01]
 [9.6961747e-05 6.5611547e-01 3.4378761e-01]
 [5.3901035e-01 4.2130402e-01 3.9685745e-02]
 [2.7490860e-01 7.2361326e-01 1.4781585e-03]
 [6.1412019e-01 3.8309959e-01 2.7801534e-03]
 [7.1604025e-01 2.8349328e-01 4.6643370e-04]], shape=(8, 3), dtype=float32)
tf.Tensor([2 2 2 1 0 1 0 0], shape=(8,), dtype=int64)
tf.Tensor([2 2 2 1 1 1 0 0], shape=(8,), dtype=int64)


In [19]:
a = np.ones([2,3,4])

In [20]:
print(a)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [23]:
np.array([[[1,2,3],[4,5,6]]]).shape

(1, 2, 3)