In [1]:
import tensorflow as tf
import numpy as np

In [ ]:
# tf.div(x,y) : elementwise operation
# tf.cast("condition") : 조건에 따라 true이면 1, false이면 0 반환



In [4]:
x_train = np.array([[1., 2.],
                    [2., 3.],
                    [3., 1.],
                    [4., 3.],
                    [5., 3.],
                    [6., 2.]], dtype = np.float32)
y_train = np.array([[0.],
                    [0.],
                    [0.],
                    [1.],
                    [1.],
                    [1.]], dtype = np.float32)

x_test = np.array([[5., 2.]], dtype=np.float32)
y_test = np.array([[1.]], dtype=np.float32)

In [14]:
# from_tensor_slices: numpy array나 list를 tensor dataset으로 변환
dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train)).batch(len(x_train))
W = tf.Variable(tf.zeros([2,1]),name = 'weight')
b = tf.Variable(tf.zeros([1], name='bias'))

def logistic_regression(features) : 
  hypothesis = tf.sigmoid(tf.matmul(features,W) + b)
  return hypothesis

def loss_fn(features, labels) :
  hypothesis = logistic_regression(features)
  cost = -tf.reduce_mean(labels * tf.math.log(hypothesis) + (1 - labels) * tf.math.log(1 - hypothesis))
  return cost

def grad(hypothesis, features, labels) :
  with tf.GradientTape() as tape :
    loss_value = loss_fn(features, labels)
  return tape.gradient(loss_value, [W,b])

optimizer = tf.keras.optimizers.SGD(learning_rate=0.01)

epochs = 3000

for step in range(epochs+1) :
  for features,labels in iter(dataset) :
    hypothesis = logistic_regression(features)
    grads = grad(hypothesis, features, labels)
    optimizer.apply_gradients(grads_and_vars=zip(grads, [W,b]))

    if step % 300 == 0 :
      print("Iter : {}, loss : {:.4f}".format(step, loss_fn(features,labels)))


Iter : 0, loss : 0.6874
Iter : 300, loss : 0.5054
Iter : 600, loss : 0.4535
Iter : 900, loss : 0.4228
Iter : 1200, loss : 0.3992
Iter : 1500, loss : 0.3790
Iter : 1800, loss : 0.3608
Iter : 2100, loss : 0.3442
Iter : 2400, loss : 0.3288
Iter : 2700, loss : 0.3146
Iter : 3000, loss : 0.3013


In [15]:

def accuracy_fn(hypothesis, labels) :
  predicted = tf.cast(hypothesis > 0.5, dtype = tf.float32)
  accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted,labels),dtype = tf.int32))
  return accuracy

test_acc = accuracy_fn(logistic_regression(x_test),y_test)
print('Accuracy : {}%'.format(test_acc*100))

Accuracy : 100%


In [7]:
dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train))

for d in dataset :
  print(d)

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>)
(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 3.], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>)
(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3., 1.], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>)
(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([4., 3.], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>)
(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([5., 3.], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>)
(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([6., 2.], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>)
